### PR TITLE
Allow to test the Nightly builds via the updateserver

### PR DESCRIPTION
**Pull request by zero-24**
With this two Update Server we are able to use the Updateserver to install the Nightly builds.

This should NOT be added to the CMS Install as option just as custom URL.

Please review / decide and merge @rdeutz @wilsonge

### CODE REVIEW

**Comment by mbabker** [comment]
Is someone adding even more options to the CMS for the update system?  This is exactly why we already have the testing option and should go back to using that for nightlies.

**Comment by mbabker** [comment]
Also, please name these correctly.  As we're using SemVer, `next_major` implies to me that should be 4.0.

**Comment by zero-24** [comment]
This should NOT been added to the CMS.

I can fix the filenames later thanks.

The problem with the testing update server is you cant say it points to 3.6.3 & 3.7.0 that is also the reason for the two different files ;)

**Comment by mbabker** [comment]
Fair point.

**Comment by zero-24** [comment]
I have fixed the filenames. We can add the major file if we have 4.0 that ready that we can provide Nightly builds ;)

**Comment by mbabker** [comment]
It's already on the nightly build page 😉 

https://developer.joomla.org/nightly-builds.html

**Comment by zero-24** [comment]
Oh sorry i have missed it. I can prepare a update server than too.

**Comment by zero-24** [comment]
Done @mbabker 

Can you double check my regex: https://github.com/joomla/update.joomla.org/pull/16/files#diff-a72e09547f3da62ee5369d8f00ba01e6R52 I'm not 100% sure if that works ;)

**Comment by mbabker** [comment]
My regex is crap too.  But if I'm reading that right it says "major versions 3 or 4 and minor versions 4 through 9", so it wouldn't match 4.0.

**Comment by zero-24** [comment]
Ahh. Correct. So i need to find something different. Thanks for checking. :+1:

**Comment by rdeutz** [comment]
is this really regex looks odd [34].[456789], wouldn't dot mean any char, if you will macht a dot you need to use \.

**Comment by zero-24** [comment]
Ah ok. Thanks :smile:

**Comment by zero-24** [comment]
@mbabker do you think we should / can add this to the Nightly Builds site? Maybe inside of the Version arcordeon? Maybe something like https://github.com/joomla-projects/plg_content_nightlybuilds/pull/1

**Comment by mbabker** [comment]
At a glance it looks fine, I'll take a better look later on when my laptop
isn't dead.

**Comment by zero-24** [comment]
:+1:

**Pull request merged**
