### PR TITLE
Nightlies do not target the right version

### PR DESCRIPTION
**Pull request by obuisard**
There are 2 possibilities for sites coming from 4.0. 4.0 and 4.0.[4.5.6].
The first one is always the one used.

### CODE REVIEW

**Comment by zero-24** [comment]
What exacly do you try to do here? When its about 4.3 this changes look wrong to me? We would need to update the list.xml and add the 4.3 packages as well as add 4.3 in the extension.xml.

**Comment by obuisard** [comment]
> What exacly do you try to do here? 

When on 4.0, the update where target is 4.0.[456] is never reached

**Comment by zero-24** [comment]
I still can not follow you can you get into a bit more detail what exact versions you are using?

This is the first source that is checked (next_minor update server):  https://github.com/joomla/update.joomla.org/blob/master/www/core/nightlies/next_minor_list.xml#L3-L6

When you are on:
- 4.0.0 -> you have targetplatform 4.0 and therefore get the update to -> 4.0.4 after that you have targetplatform 4.0.4 and get to 4.3.0-dev
- 4.0.4 you have targetplatform 4.0.4 and get to 4.3.0-dev

**Comment by richard67** [comment]
> I still can not follow you can you get into a bit more detail what exact versions you are using?
> 
> This is the first source that is checked (next_minor update server): https://github.com/joomla/update.joomla.org/blob/master/www/core/nightlies/next_minor_list.xml#L3-L6
> 
> When you are on:
> 
>     * 4.0.0 -> you have targetplatform 4.0 and therefore get the update to -> 4.0.4 after that you have targetplatform 4.0.4 and get to 4.3.0-dev
> 
>     * 4.0.4 you have targetplatform 4.0.4 and get to 4.3.0-dev

@zero-24 Like I have mentioned in the thread on Mattermost, following happens when you update a 4.2.6 to the 4.3 nightlies using the nightly build URL as custom update URL:
- When the update is found, it says it is version 4.3.0-alpha2-dev, which is correct.
- But when you perform the update, it downgrades to 4.0.4, see screenshot, and this of course fails:

2022-12-18_j4 3-update-error

**Comment by zero-24** [comment]
Please add this code `var_dump($this->updateInfo);` here: https://github.com/joomla/joomla-cms/blob/4.2-dev/administrator/components/com_joomlaupdate/tmpl/joomlaupdate/preupdatecheck.php#L100

To me it looks correct
```
array (size=5)
  'installed' => string '4.2.6' (length=5)
  'latest' => string '4.3.0-dev' (length=9)
  'object' => 
    object(Joomla\CMS\Updater\Update)[809]
      protected 'name' => 
        object(stdClass)[828]
          public '_data' => string 'Joomla! 4.3 Nightly Build' (length=25)
      protected 'description' => 
        object(stdClass)[817]
          public '_data' => string 'Joomla! CMS' (length=11)
      protected 'element' => 
        object(stdClass)[816]
          public '_data' => string 'joomla' (length=6)
      protected 'type' => 
        object(stdClass)[815]
          public '_data' => string 'file' (length=4)
      protected 'version' => 
        object(stdClass)[807]
          public '_data' => string '4.3.0-dev' (length=9)
      protected 'infourl' => 
        object(stdClass)[813]
          public '_data' => string 'https://developer.joomla.org/nightly-builds.html' (length=48)
          public 'title' => string 'Joomla! Nightly Builds' (length=22)
      protected 'client' => null
      protected 'group' => null
      protected 'downloads' => 
        object(stdClass)[787]
          public '_data' => string '
			
		' (length=7)
      protected 'downloadSources' => 
        array (size=2)
          0 => 
            object(Joomla\CMS\Updater\DownloadSource)[789]
              ...
          1 => 
            object(Joomla\CMS\Updater\DownloadSource)[788]
              ...
      protected 'tags' => 
        object(stdClass)[791]
          public '_data' => string '
			
		' (length=7)
      protected 'maintainer' => 
        object(stdClass)[825]
          public '_data' => string 'Joomla! Production Department' (length=29)
      protected 'maintainerurl' => 
        object(stdClass)[826]
          public '_data' => string 'https://www.joomla.org' (length=22)
      protected 'category' => null
      protected 'relationships' => null
      protected 'targetplatform' => 
        object(stdClass)[827]
          public '_data' => string '' (length=0)
          public 'name' => string 'joomla' (length=6)
          public 'version' => string '4.[123]' (length=7)
      protected 'extra_query' => null
      protected 'xmlParser' => resource(449, xml)
      protected 'stack' => 
        array (size=1)
          0 => string 'base' (length=4)
      protected 'stateStore' => 
        array (size=0)
          empty
      protected 'minimum_stability' => string '4' (length=1)
      protected 'compatibleVersions' => 
        array (size=1)
          0 => string '4.3.0-dev' (length=9)
      protected '_errors' => 
        array (size=0)
          empty
      public 'downloadurl' => 
        object(stdClass)[790]
          public '_data' => string 'https://developer.joomla.org/nightlies/Joomla_4.3.0-dev-Development-Update_Package.zip' (length=86)
          public 'type' => string 'full' (length=4)
          public 'format' => string 'zip' (length=3)
      public 'tag' => 
        object(stdClass)[792]
          public '_data' => string '' (length=0)
      public 'stability' => int 4
      public 'supported_databases' => 
        object(stdClass)[823]
          public '_data' => string '' (length=0)
          public 'mysql' => string '5.6' (length=3)
          public 'mariadb' => string '10.1' (length=4)
          public 'postgresql' => string '11.0' (length=4)
      public 'php_minimum' => 
        object(stdClass)[824]
          public '_data' => string '7.2.5' (length=5)
  'hasUpdate' => boolean true
  'current' => string '4.2.6' (length=5)
```

What is an problem is that the version.php within the repo is alpha2 which is wrong for this dev package: https://github.com/joomla/joomla-cms/blob/4.3-dev/libraries/src/Version.php#L69

So even when this XML looks correct to me the update fails as the download file is not aviable.

**Comment by richard67** [comment]
@zero-24 I think the extra version and the "alpha-2dev" part of the download URL are right, and the package can be downloaded fine with that URL https://developer.joomla.org/nightlies/Joomla_4.3.0-alpha2-dev-Development-Update_Package.zip from this site https://developer.joomla.org/nightly-builds.html .

The problem is that the URL in the next_minor_extension.xml is wrong. It is https://developer.joomla.org/nightlies/Joomla_4.3.0-dev-Development-Update_Package.zip , but it should be https://developer.joomla.org/nightlies/Joomla_4.3.0-alpha2-dev-Development-Update_Package.zip .

But of course you can also say vice versa, that the first one is wrong and the second one is right.

However I would prefer the first way being used. As soon as we have some kind of release, starting with alpha, we should do it that way, so when 4.3.0-alpha2 has been released it will be 4.3.0-alpha3 (or 4.3.0-beta1, depending on our release schedule) in the name, like I know it from @wilsonge .

**Comment by zero-24** [comment]
> @zero-24 I think the extra version and the "alpha-2dev" part of the download URL are right, and the package can be downloaded fine with that URL https://developer.joomla.org/nightlies/Joomla_4.3.0-alpha2-dev-Development-Update_Package.zip from this site https://developer.joomla.org/nightly-builds.html .

Yes but that URL is not set in the extension.xml and therfore the updater will try to update via an 404er URL.

> The problem is that the URL in the next_minor_extension.xml is wrong. It is https://developer.joomla.org/nightlies/Joomla_4.3.0-dev-Development-Update_Package.zip , but it should be https://developer.joomla.org/nightlies/Joomla_4.3.0-alpha2-dev-Development-Update_Package.zip .

I do disagree. Its part of the release checklist to reset it back to dev without alpha what ever ;)

> However I would prefer the first way being used. As soon as we have some kind of release, starting with alpha, we should do it that way, so when 4.3.0-alpha2 has been released it will be 4.3.0-alpha3 (or 4.3.0-beta1, depending on our release schedule) in the name, like I know it from @wilsonge .

We did it different in the past but if anything that would not solve the issue here. Lets await what the result of the proposed check is so we better understand the issue: https://github.com/joomla/update.joomla.org/pull/277#issuecomment-1356845779

**Comment by richard67** [comment]
> Lets await what the result of the proposed check is so we better understand the issue:

@zero-24 What shall that be good for? We already know that either the download URL in the next_minor_extension.xml is wrong, what I think and you not, or the URL on https://developer.joomla.org/nightly-builds.html is wrong, what you say. This has to be fixed so or so.

**Comment by zero-24** [comment]
> @zero-24 What shall that be good for? We already know that either the download URL in the next_minor_extension.xml is wrong, what I think and you not, or the URL on https://developer.joomla.org/nightly-builds.html is wrong, what you say. This has to be fixed so or so.

This is a secondary issue. The primary issue is that for some reason @obuisard got a downgrade and therefore i would like to understand what he got on the check maybe some other code is wrong too?

**Comment by richard67** [comment]
> This is a secondary issue. The primary issue is that for some reason @obuisard got a downgrade and therefore i would like to understand what he got on the check maybe some other code is wrong too?

@zero-24 It was me who got that downgrade.

**Comment by zero-24** [comment]
Than please do you add said code and let me know the result :)

**Comment by richard67** [comment]
@zero-24 Ok, here is your var_dump:

```
/home/richard/lamp/public_html/test-1/administrator/components/com_joomlaupdate/tmpl/joomlaupdate/preupdatecheck.php:100:
array (size=5)
  'installed' => string '4.2.6' (length=5)
  'latest' => string '4.3.0-dev' (length=9)
  'object' => 
    object(Joomla\CMS\Updater\Update)[834]
      protected '_errors' => 
        array (size=0)
          empty
      protected 'name' => 
        object(stdClass)[858]
          public '_data' => string 'Joomla! 4.3 Nightly Build' (length=25)
      protected 'description' => 
        object(stdClass)[853]
          public '_data' => string 'Joomla! CMS' (length=11)
      protected 'element' => 
        object(stdClass)[874]
          public '_data' => string 'joomla' (length=6)
      protected 'type' => 
        object(stdClass)[875]
          public '_data' => string 'file' (length=4)
      protected 'version' => 
        object(stdClass)[872]
          public '_data' => string '4.3.0-dev' (length=9)
      protected 'infourl' => 
        object(stdClass)[876]
          public '_data' => string 'https://developer.joomla.org/nightly-builds.html' (length=48)
          public 'title' => string 'Joomla! Nightly Builds' (length=22)
      protected 'client' => null
      protected 'group' => null
      protected 'downloads' => 
        object(stdClass)[818]
          public '_data' => string '
			
		' (length=7)
      protected 'downloadSources' => 
        array (size=2)
          0 => 
            object(Joomla\CMS\Updater\DownloadSource)[855]
              ...
          1 => 
            object(Joomla\CMS\Updater\DownloadSource)[856]
              ...
      protected 'tags' => 
        object(stdClass)[854]
          public '_data' => string '
			
		' (length=7)
      protected 'maintainer' => 
        object(stdClass)[860]
          public '_data' => string 'Joomla! Production Department' (length=29)
      protected 'maintainerurl' => 
        object(stdClass)[859]
          public '_data' => string 'https://www.joomla.org' (length=22)
      protected 'category' => null
      protected 'relationships' => null
      protected 'targetplatform' => 
        object(stdClass)[835]
          public '_data' => string '' (length=0)
          public 'name' => string 'joomla' (length=6)
          public 'version' => string '4.[123]' (length=7)
      protected 'extra_query' => null
      protected 'xmlParser' => 
        object(XMLParser)[813]
      protected 'stack' => 
        array (size=1)
          0 => string 'base' (length=4)
      protected 'stateStore' => 
        array (size=0)
          empty
      protected 'currentUpdate' => *uninitialized*
      protected 'latest' => *uninitialized*
      protected 'minimum_stability' => string '0' (length=1)
      protected 'compatibleVersions' => 
        array (size=1)
          0 => string '4.3.0-dev' (length=9)
      public 'downloadurl' => 
        object(stdClass)[819]
          public '_data' => string 'https://developer.joomla.org/nightlies/Joomla_4.3.0-dev-Development-Update_Package.zip' (length=86)
          public 'type' => string 'full' (length=4)
          public 'format' => string 'zip' (length=3)
      public 'tag' => 
        object(stdClass)[852]
          public '_data' => string '' (length=0)
      public 'stability' => int 4
      public 'supported_databases' => 
        object(stdClass)[863]
          public '_data' => string '' (length=0)
          public 'mysql' => string '5.6' (length=3)
          public 'mariadb' => string '10.1' (length=4)
          public 'postgresql' => string '11.0' (length=4)
      public 'php_minimum' => 
        object(stdClass)[862]
          public '_data' => string '7.2.5' (length=5)
  'hasUpdate' => boolean true
  'current' => string '4.2.6' (length=5)
```
I do not see any significant difference to your var_dump except some differences which could be caused by a different minimum stability setting. But the found versions are the same.

But as I said, the problem does not happen when the update is found. It shows the right version being found. The problem happens when the update is executed.

**Comment by zero-24** [comment]
Ok I have debugged the issue. The issue here is that the download URL is 404*ing and the downloadsource object is not cleared. In this case its that we have the $this->downloadSources object still existing and therfore thats used. An fix here could be that we remove the other download sources will send a fix to the CMS which makes sure that this issue does not come up again.

**Comment by zero-24** [comment]
PR created: https://github.com/joomla/joomla-cms/pull/39446#issue-1502010986 

@richard67 please confirm that its working for you with that change as well so we can close this here in favor of said patch. As workaround for existing setups I would propose that we remove the downloadsource tags from here: https://github.com/joomla/update.joomla.org/blob/master/www/core/nightlies/next_minor_extension.xml#L31-L32

And also fix the version.php within the joomla repo so that the nighly build generate the matching URL ;)

Please await merging the changes to the version.php until said PR has been tested else we could not reproduce the issue anymore :)

**Comment by zero-24** [comment]
@obuisard please review and merge: https://github.com/joomla/update.joomla.org/pull/278

This here should be closed as it does not fix the issue itself, the underlying issue is fixed via https://github.com/joomla/joomla-cms/pull/39446

The seccond thing which needs correcting is the Version.php which should be reset to -dev or the update xml download URLs and Version numbers need to be updated within the XMLs

**Comment by obuisard** [comment]
Resolution found at #278

**Comment by richard67** [comment]
@obuisard You can use my custom update URL's for testing it, see https://github.com/joomla/update.joomla.org/pull/278#issuecomment-1357328777 .

**Pull request closed without merging**
