### PR TITLE
3.6.3 stable

### PR DESCRIPTION
**Pull request by zero-24**
This just change the update server to point to 3.6.3.

Before the merge (this is a upstream branch so you can edit it before the merge!) please change this line https://github.com/joomla/update.joomla.org/blob/3.6.3/www/core/sts/extension_sts.xml#L136 to the correct URL on joomla.org!

### CODE REVIEW

**Comment by mbabker** [comment]
You've deleted too much here.  As is this will force all updates to use the update package (which is technically fine since all files are there), but we purposefully have definitions to use the smaller patch packages when updating from 3.6.x to 3.6.3.

**Comment by mbabker** [comment]
You need four `<update>` tags with each of the following target platforms:

`<targetplatform name="joomla" version="3.2" min_dev_level="2" />` (we've been keeping this one to enforce users on 3.2.1 and earlier to get to a version that had the PHP minimum check before going higher because of that change in 3.3)
`<targetplatform name="joomla" version="3.[345]" />` for 3.3-5 (all updates)
`<targetplatform name="joomla" version="3.6.[01]" /> for the 3.6.x to 3.6.3 patch package
`<targetplatform name="joomla" version="3.6.2" /> for the 3.6.2 to 3.6.3 patch package

It was either 3.5 or 3.6 that deprecated the `min_dev_level` attribute in favor of being able to use the full version in that attribute instead of major.minor only, so this should work just fine.

**Comment by zero-24** [comment]
since we use the update URL also for reinstall we can't use the smaler package ;)

We need this one (or any similiar) merged to use the smaler packages again: https://github.com/joomla/joomla-cms/pull/11497

**Comment by rdeutz** [comment]
@zero-24 could you have a look here, thanks

**Comment by zero-24** [comment]
Yes tomorrow i can fix the conflicts. I'm not at my PC today :)

**Comment by zero-24** [comment]
Should be fine now :smile:

**Pull request merged**
