### PR TITLE
remove download source as a workaround for existing sites

### PR DESCRIPTION
**Pull request by zero-24**
cc @richard67 @obuisard

ref: https://github.com/joomla/joomla-cms/pull/39446

### CODE REVIEW

**Comment by richard67** [comment]
I've created update sites for testing, which point to extension.xml files which contain the changes from this PR here plus the change to make the nightly download URLs not being valid. But I won't be able to test before tonight. It needs to test if the right error message is shown for the nightly build and not a downgrade to 4.0.4 happens, and it should also be tested if updating a 4.0.3 or earlier 4.0.x to 4.0.4 still works as before. Here the custom update URL's:
- https://test5.richard-fath.de/next_major_list_2.xml
- https://test5.richard-fath.de/next_minor_list_2.xml
- https://test5.richard-fath.de/next_patch_list_2.xml

**Comment by richard67** [comment]
Well, I have found a little bit time to test all my 3 update URL's (see previous comment) if they show the right target version when the update is found and show the right error message about download failed when attempting to update instead of making a downgrade to 4.0.4. All 3 tests were successful.

What remains to be tested by me is the 2nd part of the test that on a 4.0.3 or earlier 4.0.x an update to 4.0.4 is found, and you can update to that version.

**Comment by richard67** [comment]
Now I've also tested the 2nd part with success, updating a 4.0.3 to 4.0.4, with all my 3 custom update URL's. The test needs to be done on a PHP version < 8, otherwise you run into the problem described here: https://github.com/joomla/joomla-cms/issues/36185 . When only having PHP 8 for testing, do as advised in a comment in that issue: Manually apply the changes from https://github.com/joomla/joomla-cms/pull/36041 before the update. This will make the update work, but after that the error comes back because that PR was merged into 4.0.5. But that's not related to the thing here.

So all in all I have tested this PR here with success. :white_check_mark:

**Review by obuisard — APPROVED** [review]

**Comment by obuisard** [comment]
I have tested the PR successfully, following @richard67 recommendations. Thank you Richard for providing the test files.

**Comment by zero-24** [comment]
Feel free to merge @obuisard :)

**Comment by obuisard** [comment]
Thank you, Tobias @zero-24 for your help on this!

**Comment by zero-24** [comment]
Np now we need to fix the donload URL and version here on better in the version.php on the CMS repo

**Pull request merged**
