### PR TITLE
Make the update availiable for beta1 -> beta2 Updates

### PR DESCRIPTION
**Pull request by zero-24**
Show the update also for targetplatformversion 3.5

### CODE REVIEW

**Comment by brianteeman** [comment]
There is no update path for beta releases.

**Comment by brianteeman** [comment]
Oops hit send too early.

Supporting updates from beta release to beta release or even stable has
always been considered the wrong thing to do. It can encourage people to
use a beta on a live site. Not even sure if we have the dB updates or file
update scripts for beta to beta

**Comment by zero-24** [comment]
Yes but we need this entrys for the final version. But feel free to close :smile:

**Comment by mbabker** [comment]
Technically, the blocker for beta path upgrades was when all the database schema updates went into one single file.  When we went back to using dated schema files, it silently resolved the upgrade path issue.  The only thing that won't change is how the deleted file/folder listing is managed; stuff that gets added and removed between two stable releases won't ever get put in there (meaning if something is added, a beta goes out, then it's moved/deleted Joomla won't auto-delete it).

That said, given the utf8mb4 issue, I get the feeling that schema files are going to be modified so that's going to mean the upgrade path at the database level gets broken.

**Comment by brianteeman** [comment]
> The only thing that won't change is how the deleted file/folder listing
is managed; stuff that gets added and removed between two stable releases
won't ever get put in there (meaning if something is added, a beta goes
out, then it's moved/deleted Joomla won't auto-delete it).

Which could end up being a security issue.

We dont want people to use a beta on a live site so I really see no need to
allow a beta to be updated. If we do then we will only see people
installing it on live sites

On 29 January 2016 at 13:18, Michael Babker <notifications@github.com>
wrote:

> Technically, the blocker for beta path upgrades was when all the database
> schema updates went into one single file. When we went back to using dated
> schema files, it silently resolved the upgrade path issue. The only thing
> that won't change is how the deleted file/folder listing is managed; stuff
> that gets added and removed between two stable releases won't ever get put
> in there (meaning if something is added, a beta goes out, then it's
> moved/deleted Joomla won't auto-delete it).
>
> That said, given the utf8mb4 issue, I get the feeling that schema files
> are going to be modified so that's going to mean the upgrade path at the
> database level gets broken.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/update.joomla.org/pull/4#issuecomment-176750428>
> .
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by mbabker** [comment]
If this were going into the stable channel I'd agree.  At face value, I see it no worse than when the nightly builds for the next release in the testing channel (and those truly had no upgrade path until a stable release was tagged).

**Pull request closed without merging**
