### PR TITLE
remove the french helpsite

### PR DESCRIPTION
**Pull request by alikon**
if and when https://github.com/joomla/joomla-cms/pull/22133 will be merged,
then we should decide when this one can be safely merged

### CODE REVIEW

**Comment by infograf768** [comment]
"Normally", it would be nice to wait for joomla.fr to make a redirection.

**Comment by agerix** [comment]
we'll take care of it, I'll come back to you as soon as it's done

**Comment by alikon** [comment]
just to update the reference 
the current cms pr is now: https://github.com/joomla/joomla-cms/pull/24927

**Comment by HLeithner** [comment]
We can merge this on Joomla 3.9.7 release, planned for 2019-06-11

**Pull request merged**
