### PR TITLE
Remove never needed nor used JED Update Server from new installs

### PR DESCRIPTION
**Pull request by zero-24**
see here for the CMS PR: https://github.com/joomla/joomla-cms/pull/13047 which should be merged first.

### CODE REVIEW

**Comment by zero-24** [comment]
Please remember this to be pushed ;)

**Comment by wilsonge** [comment]
FFS. Yes I forgot. Removed and committed now. Sorry

**Comment by zero-24** [comment]
Ahh my comment got missed.

We can't remove this file today we need to wait for 3.7.x or even give it a bit time too ;).

**Comment by zero-24** [comment]
As now every joomla install indicate them as disabled and they will be shown in com_joomlaupdate so please revert the change until we have a final 3.7 or even 3.7.1/2

**Comment by wilsonge** [comment]
Reverted :)

**Comment by zero-24** [comment]
Thanks 👍

**Pull request closed without merging**
