### PR TITLE
Joomla 3.2.7 -> 3.6.4 update download

### PR DESCRIPTION
**Pull request by zero-24**
Fixes: https://github.com/joomla/update.joomla.org/issues/28

@andrepereiradasilva Please test via http://www.jah-tz.de/downloads/core/list4.xml

### CODE REVIEW

**Comment by andrepereiradasilva** [comment]
works here thanks!

**Comment by zero-24** [comment]
:+1: @rdeutz @wilsonge please review and push to the server.

**Comment by dgt41** [comment]
@zero-24 shouldn't `targetplatformversion="3.2.7"` be `targetplatformversion="3.2"` ??

**Comment by mbabker** [comment]
3.2.3+ should be allowed to direct update to 3.3+ if they meet the PHP minimum.  So yes, it should stay as 3.2 IMO unless there's some new bugged reason why this can't work (which only further reinforces the need to rewrite the update system to stop using this bugged XML parser).

**Comment by mbabker** [comment]
Didn't I have a rant/RFC somewhere about refactoring the update system to a remote app (almost similar to how WordPress' updates are checked if you've ever reverse engineered that)?  Or am I dreaming again?

**Comment by zero-24** [comment]
> somewhere about refactoring the update system to a remote app

sounds great. Let me know if i can help you in any meaning with that!

**Comment by mbabker** [comment]
Oh, it was https://github.com/joomla/joomla-cms/issues/12351#issuecomment-252430961 that I was thinking of.  Not a full blown issue on its own.

**Comment by zero-24** [comment]
I'm here if we want to start the work on a new updater ;) but i guess we should fix the current problem first?

**Comment by andrepereiradasilva** [comment]
more users with this problem  https://forum.joomla.org/viewtopic.php?f=710&t=937843

**Comment by wilsonge** [comment]
Also just pushed to the server

**Comment by zero-24** [comment]
:heart:

**Pull request merged**
